# Generated by Django 5.2.15 on 2026-06-11 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=50, unique=True)),
                ('control_name', models.CharField(max_length=255)),
                ('control_code', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('function_group', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_controls', to=settings.AUTH_USER_MODEL)),
                ('action_teams', models.ManyToManyField(related_name='control_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(max_length=50, unique=True)),
                ('evidence_code', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
                ('action_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_owner', to=settings.AUTH_USER_MODEL)),
                ('action_teams', models.ManyToManyField(related_name='evidence_teams', to=settings.AUTH_USER_MODEL)),
                ('controls', models.ManyToManyField(related_name='evidence_controls', to='grc.control')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=50, unique=True)),
                ('policy_name', models.CharField(max_length=255)),
                ('policy_code', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_policies', to=settings.AUTH_USER_MODEL)),
                ('action_teams', models.ManyToManyField(related_name='policy_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc.policy'),
        ),
    ]
